package woven_bank;

// Start of user code for imports
// End of user code

/**
 * LogToScreen class definition.
 * Generated by the TouchCORE code generator.
 */
class LogToScreen {
    
    void log(String message) {
        System.out.println(message);
    }
}
